In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## pandas Series  --> 1Demnions data

In [2]:
series1 = pd.Series(1, name='names')

In [3]:
series1 = pd.Series([1, 2, np.nan, 4], name='names')
print(series1.name)
print(series1.index)
print(series1.values)
print(series1)

series1.name = 'renamed'
print(series1)

names
RangeIndex(start=0, stop=4, step=1)
[ 1.  2. nan  4.]
0    1.0
1    2.0
2    NaN
3    4.0
Name: names, dtype: float64
0    1.0
1    2.0
2    NaN
3    4.0
Name: renamed, dtype: float64

## Dataframes  --> 2Dimension data

In [4]:
df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns= ['a', 'b', 'c'])
df.index.to_list()

# index advantages
df.index = df['a'] # reaplce default index with a column 
df = df[df.index % 2 == 0] # we can perfrom filter operations using index or based on datatype of index

### outliers

In [5]:
arr = np.random.randint(5, 10, size=(25, 2))
df = pd.DataFrame(arr, columns=['A', 'B'])

In [43]:
n_outliers = 3
indices = np.random.choice(df.index, size=n_outliers, replace=False)

# add large outliers to column A
df.loc[indices, 'A'] = np.random.randint(50, 100, size=n_outliers)

In [44]:
q1 = df['A'].quantile(0.25)
q3 = df['A'].quantile(0.75)
iqr = q3 - q1

lower_outlier = q1 - 1.5 * iqr
upper_outlier = q3 + 1.5 * iqr

outliers_A = df.loc[
    (df['A'] < lower_outlier) | (df['A'] > upper_outlier),
    ['A']
]

outliers_A

     A
16  51
19  55
24  88

### random practice

In [6]:
employee = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen"],
    "age": [24, 32, 29, 45, 38, 27, 41, 35],
    "department": ["HR", "IT", "Finance", "IT", "Marketing", "Finance", "Operations", "HR"],
    "salary": [35000, 85000, 65000, 120000, 72000, 58000, 98000, 42000]
}
emp_df = pd.DataFrame(employee)
department = {
    "department": ["HR", "IT", "Finance", "Marketing", "Operations"],
    "manager": ["Alice", "Bob", "Charlie", "Eva", "Grace"],
    "location": ["New York", "Bangalore", "London", "Mumbai", "Berlin"]
}
dprt_df = pd.DataFrame(department)

In [ ]:
# Data Loading --> pd.read_csv(), pd.read_excel(), pd.read_sql()
# Data Inspection --> df.head(), df.tail(), df.info(), df.shape, df.describe()
# Data Cleaning --> df.isna(), df.fillna(), df.dropna(), df.duplicated(), df.drop_duplicates()
# Data Type Correction --> df.astype(), pd.to_datetime()
# Data Filtering & Selection --> df.loc[], df.iloc[], df.query()
# Feature Engineering --> df['new_col'], df.apply(), df.assign()
# Data Transformation --> df.map(), df.replace(), np.where()
# Aggregation & Grouping --> df.groupby(), .agg(), .mean(), .sum()
# Merging & Joining --> pd.merge(), df.join(), pd.concat()
# Sorting & Reshaping --> df.sort_values(), df.pivot(), df.melt()
# Validation & Export --> df.isna().sum(), df.to_csv(), df.to_excel()

##### loc, iat

In [ ]:
# Label-based indexing - 
# can give strings / boolean condition / array of strings and columns should be mentioned 

# Single label → df.loc[2, 'Name']
# List of labels → df.loc[[1,3], ['Name','Age']]
# Slice by labels → df.loc['row1':'row4', 'col1':'col3']
# Boolean conditions → df.loc[df['Age']>25]

# emp_df.loc[:4, ['name','department','salary','age']]

In [ ]:
# map
df = pd.DataFrame({'A': [1, 2, 3, 4]})
df['A'] = df['A'].map(lambda x: x*2)

In [127]:
df = pd.DataFrame({'color': ['red', 'green', 'blue']})

df['color'] = df['color'].map({'red': 'R', 'green': 'G', 'blue': 'B'})
print(df)

  color
0     R
1     G
2     B

In [128]:
df = pd.DataFrame({'A': [1, 2, 3, 2, 1]})

df.replace(1, 10, inplace=True)
print(df)

df.replace([1, 2], [10, 20])
df.replace({'A': {1: 10, 2: 20}, 'B': {'x': 'X'}})

    A
0  10
1   2
2   3
3   2
4  10

    A
0  10
1  20
2   3
3  20
4  10

##### groupby

In [7]:
# # Group by Team and calculate multiple stats for Score and Assists
# result = df.groupby('Team').agg({
#     'Score': ['sum', 'mean', 'max'],
#     'Assists': ['sum', 'mean']
# })

# # Multiple aggregations with renamed columns
# result = df.groupby('Team').agg(
#     total_score=('Score', 'sum'),
#     avg_score=('Score', 'mean'),
#     max_assists=('Assists', 'max')
# )

# Employee dataset
employee = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen",
             "Ian", "Jack", "Kelly", "Laura", "Mike", "Nina", "Oscar", "Pam", "Quinn", "Ryan"],
    "age": [24, 32, 29, 45, 38, 27, 41, 35, 28, 31, 26, 40, 33, 29, 37, 42, 34, 30],
    "department": ["HR", "IT", "Finance", "IT", "Marketing", "Finance", "Operations", "HR",
                   "IT", "Marketing", "Finance", "Operations", "IT", "HR", "Marketing", "Finance", "Operations", "IT"],
    "salary": [35000, 85000, 65000, 120000, 72000, 58000, 98000, 42000,
               90000, 75000, 60000, 102000, 88000, 40000, 77000, 59000, 99000, 87000],
    "experience": [1, 8, 5, 20, 10, 4, 15, 6, 7, 9, 3, 18, 12, 2, 11, 6, 16, 8],  # in years
    "bonus_pct": [5, 15, 10, 20, 12, 8, 18, 6, 14, 12, 7, 19, 16, 5, 13, 9, 17, 15]  # percentage
}

emp_df = pd.DataFrame(employee)

# Department dataset
department = {
    "department": ["HR", "IT", "Finance", "Marketing", "Operations"],
    "manager": ["Alice", "Bob", "Charlie", "Eva", "Grace"],
    "location": ["New York", "Bangalore", "London", "Mumbai", "Berlin"]
}

dprt_df = pd.DataFrame(department)

# Merge department info into employee
emp_df = emp_df.merge(dprt_df, on="department", how="left")

print(emp_df.head(10))

      name  age  department  salary  experience  bonus_pct  manager   location
0    Alice   24          HR   35000           1          5    Alice   New York
1      Bob   32          IT   85000           8         15      Bob  Bangalore
2  Charlie   29     Finance   65000           5         10  Charlie     London
3    David   45          IT  120000          20         20      Bob  Bangalore
4      Eva   38   Marketing   72000          10         12      Eva     Mumbai
5    Frank   27     Finance   58000           4          8  Charlie     London
6    Grace   41  Operations   98000          15         18    Grace     Berlin
7    Helen   35          HR   42000           6          6    Alice   New York
8      Ian   28          IT   90000           7         14      Bob  Bangalore
9     Jack   31   Marketing   75000           9         12      Eva     Mumbai

In [8]:
# the following create a series 
grp = emp_df.groupby('department')['salary'].sum()
print(type(grp))

# the following creates a series 
grp1 = emp_df.groupby('department').agg({'salary':'sum'})
print(type(grp1))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
salary_insights =

In [85]:
# Team Salary Insights
# Find the total salary, average salary, and maximum salary per department.
# Include number of employees per department.
############################################################## reset index emp_df.groupby('department', as_index=False)
salary_insights = emp_df.groupby('department').agg( emp_count = ('department','count'),
                                                    total_salary=('salary','sum'),
                                                   max_salary=('salary', 'max'),
                                                   min_salary=('salary','min')
                                                   ).reset_index()
salary_insights

   department  emp_count  total_salary  max_salary  min_salary
0     Finance          4        242000       65000       58000
1          HR          3        117000       42000       35000
2          IT          5        470000      120000       85000
3   Marketing          3        224000       77000       72000
4  Operations          3        299000      102000       98000

In [98]:
# Bonus Efficiency
# Calculate actual bonus for each employee (salary * bonus_pct / 100).
# Then find the average bonus by manager.

emp_df['bonus'] = emp_df['salary'] * emp_df['bonus_pct'] / 100

bonus_df = emp_df.groupby('manager', as_index=False)['bonus'].mean()
bonus_df

   manager         bonus
0    Alice   2090.000000
1      Bob  15296.000000
2  Charlie   5162.500000
3      Eva   9216.666667
4    Grace  17950.000000

In [99]:
# Include total bonus along with average

bonus_df = emp_df.groupby('manager', as_index=False).agg(total_bonus=('bonus', 'sum'),
                                         avg_bonus=('bonus','mean'))
bonus_df

   manager  total_bonus     avg_bonus
0    Alice       6270.0   2090.000000
1      Bob      76480.0  15296.000000
2  Charlie      20650.0   5162.500000
3      Eva      27650.0   9216.666667
4    Grace      53850.0  17950.000000

In [ ]:
# Sort managers by highest average bonus
# sort values multi index  bonus_df.sort_values(['avg_bonus', 'department], ascending=[0,1])

bonus_df = bonus_df.sort_values(by='avg_bonus')
bonus_df

   manager  total_bonus     avg_bonus
0    Alice       6270.0   2090.000000
1  Charlie      20650.0   5162.500000
2      Eva      27650.0   9216.666667
3      Bob      76480.0  15296.000000
4    Grace      53850.0  17950.000000

In [104]:
emp_df.columns

Index(['name', 'age', 'department', 'salary', 'experience', 'bonus_pct',
       'manager', 'location', 'bonus'],
      dtype='object')

In [ ]:
# Top Performers
# Find the employee with maximum experience in each department.
# Show their name, experience, salary, and location.

top_performer_idx = emp_df.groupby('department')['experience'].idxmax()
top_performer = emp_df.loc[top_performer_idx, ['name', 'department', 'experience', 'salary', 'location'] ]
top_performer

     name  department  experience  salary   location
15    Pam     Finance           6   59000     London
7   Helen          HR           6   42000   New York
3   David          IT          20  120000  Bangalore
14  Oscar   Marketing          11   77000     Mumbai
11  Laura  Operations          18  102000     Berlin

In [110]:
# Department Filtering
# List departments where the average salary is above 80,000.

deprt_avg_salary = emp_df.groupby('department', as_index=False)['salary'].mean()

deprt_filtr =  deprt_avg_salary[ deprt_avg_salary['salary'] > 80000]
deprt_filtr

   department        salary
2          IT  94000.000000
4  Operations  99666.666667

In [ ]:
# Normalized Salary
# Create a new column salary_norm which shows salary normalized by department total salary using transform.
# Check if sum of salary_norm per department equals 1.

emp_df['salary_norm'] = emp_df['salary'] / emp_df.groupby('department')['salary'].transform('sum')
deprt_salary_norm_total = emp_df.groupby('department')['salary_norm'].sum().reset_index()
deprt_salary_norm_total['flag'] = deprt_salary_norm_total['salary_norm'].map(lambda x: 1 if x == 1 else 0)


# emp_df['high_earner_flag'] = emp_df.apply(
#     lambda row: 1 if (row['salary_norm'] > 0.2) and (row['bonus'] > 10000) else 0,
#     axis=1
# )

   department  salary_norm
0     Finance          1.0
1          HR          1.0
2          IT          1.0
3   Marketing          1.0
4  Operations          1.0

##### col string operations

In [ ]:
# --- PANDAS STRING METHODS CHEATSHEET ---

# 1. CASE TRANSFORMATION
df['col'].str.lower()      # Convert to lowercase
df['col'].str.upper()      # Convert to uppercase
df['col'].str.title()      # Convert to Title Case
df['col'].str.capitalize() # Capitalize first letter only

# 2. CLEANING & REPLACING
df['col'].str.strip()      # Remove leading and trailing whitespace
df['col'].str.lstrip()     # Remove whitespace on the left
df['col'].str.rstrip()     # Remove whitespace on the right
df['col'].str.replace('old', 'new') # Replace text (supports regex)

# 3. FILTERING & SEARCHING (Returns Boolean True/False)
df[df['col'].str.contains('keyword')]   # Check if string contains a substring
df[df['col'].str.startswith('prefix')]  # Check if string starts with prefix
df[df['col'].str.endswith('suffix')]    # Check if string ends with suffix
df[df['col'].str.match(r'^Regex')]      # Check if matches a regex pattern

# 4. SPLITTING & EXTRACTING
df['col'].str.split(' ')            # Split into a list of strings
df['col'].str.split(' ', expand=True) # Split into multiple NEW columns
df['col'].str.get(0)                # Get the element at index 0 (useful after split)
df['col'].str.extract(r'(\d+)')     # Extract first numeric match into a new column

# 5. INFORMATION & SLICING
df['col'].str.len()                 # Get length of each string
df['col'].str.slice(0, 5)           # Slice string (same as [0:5])
df['col'].str.count('a')            # Count occurrences of a character/pattern

# 6. PADDING & ENCODING
df['col'].str.zfill(5)              # Pad with zeros (e.g., '1' becomes '00001')
df['col'].str.pad(width=10, side='left', fillchar='-') # Custom padding

In [ ]:
df['converted_text'] = np.where(
    has_special_chars, 
    df['original_text'], 
    df['original_text'].str.title()
)

##### datetime operations

In [ ]:
df['date_col'] = pd.to_datetime(df['col'])

# Assuming df['date_col'] is already converted via pd.to_datetime()

# 1. Extraction
df['year']  = df['date_col'].dt.year
df['month'] = df['date_col'].dt.month
df['day']   = df['date_col'].dt.day
df['hour']  = df['date_col'].dt.hour

# 2. Names and Labels
df['day_name']   = df['date_col'].dt.day_name()   # 'Monday', 'Tuesday'
df['month_name'] = df['date_col'].dt.month_name() # 'January'

# 3. Period/Frequency Logic
df['quarter']    = df['date_col'].dt.quarter      # 1, 2, 3, or 4
df['is_weekend'] = df['date_col'].dt.dayofweek > 4 # True for Sat/Sun
df['is_leap']    = df['date_col'].dt.is_leap_year

# 4. Formatting
df['formatted'] = df['date_col'].dt.strftime('%Y-%m') # Custom strings (e.g., '2023-12')

##### categorical operations

In [ ]:
# Convert to category first
df['size'] = df['size'].astype('category')

# 1. View Categories
print(df['size'].cat.categories)

# 2. Reorder Categories (Crucial for plotting/sorting)
df['size'] = df['size'].cat.reorder_categories(['Small', 'Medium', 'Large'], ordered=True)

# 3. Add or Remove Categories
df['size'] = df['size'].cat.add_categories(['Extra Large'])
df['size'] = df['size'].cat.remove_unused_categories()

# 4. Rename Categories
df['size'] = df['size'].cat.rename_categories({'S': 'Small', 'M': 'Medium'})

##### groupby

In [ ]:
# MATH - Basic Aggregation

df.groupby('dept')['salary'].sum()     # Total
df.groupby('dept')['salary'].mean()    # Average
df.groupby('dept')['salary'].median()  # Middle value
df.groupby('dept')['salary'].std()     # Standard Deviation
df.groupby('dept')['salary'].var()     # Variance

# COUNTS & EXTREMES
df.groupby('dept')['id'].count()       # Count non-null values
df.groupby('dept')['id'].nunique()     # Count unique values
df.groupby('dept')['salary'].min()     # Minimum
df.groupby('dept')['salary'].max()     # Maximum
df.groupby('dept')['salary'].first()   # First row in group
df.groupby('dept')['salary'].last()    # Last row in group

# Advanced Aggregation
# Multiple functions at once
df.groupby('dept')['salary'].agg(['mean', 'sum', 'count'])

# Named Aggregation (Best for clean columns)
df.groupby('dept').agg(
    avg_pay=('salary', 'mean'),
    max_exp=('experience', 'max'),
    staff_count=('id', 'count')
)

# Transformation & Filtration
# 1. TRANSFORMATION
# Returns a Series the SAME LENGTH as the original df.
# Useful for: "What is this person's salary vs the dept average?"
df['dept_avg'] = df.groupby('dept')['salary'].transform('mean')

# 2. FILTRATION
# Discards entire groups based on a condition.
# Keeps only depts with more than 10 employees:
df.groupby('dept').filter(lambda x: len(x) > 10)

# 3. APPLY
# The "Swiss Army Knife" - can return anything.
df.groupby('dept').apply(lambda x: x.nlargest(2, 'salary'))



# Rank employees by salary within their own department
df['dept_rank'] = df.groupby('department')['salary'].rank(method='dense', ascending=False)